receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1000
  memory_limiter:
    check_interval: 1s
    limit_mib: 500
    spike_limit_mib: 100
  filter:
    metrics:
      include:
        match_type: regexp
        metric_names:
          - ".*"

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: go_otel
    send_timestamps: true
    metric_expiration: 180m
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, filter]
      exporters: [prometheus, logging]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]
  
  # Add health check extension
  extensions: [health_check]
  telemetry:
    logs:
      level: "debug"

extensions:
  health_check:
    endpoint: 0.0.0.0:13133